/**
 * flatwrite.md - Minimalist Markdown Editor
 *
 * Copyright (C) 2026 Mahesh Shantaram
 * Sole Proprietary Owner. All Rights Reserved.
 *
 * This file is part of flatwrite.md.
 * flatwrite.md is free software: you can redistribute it or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * For commercial, closed-source embedding, and SaaS deployment exemptions,
 * a valid Commercial License Agreement is required. Contact: sales@flatwrite.md
 */

/**
 * Regression test: every font in the canonical inventory must have a
 * corresponding woff2 file on disk, the file must start with the wOF2
 * magic, and the auto-generated public/fonts.css must declare it.
 *
 * The single source of truth is core/font-inventory.js. Both
 * core/font-loader.js (server-side render, embeds as data URI) and
 * scripts/build-fonts-css.mjs (browser-side CSS, links woff2 files)
 * consume from there. This test pins down the invariants so the
 * picker, preview, and rendered output can't drift out of sync.
 */

import { describe, test, expect } from "bun:test";
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..");
const INVENTORY = resolve(REPO_ROOT, "core/font-inventory.js");
const FONT_DIR = resolve(REPO_ROOT, "public/fonts");
const FONTS_CSS = resolve(REPO_ROOT, "public/fonts.css");
const FONT_LOADER = resolve(REPO_ROOT, "core/font-loader.js");
const INDEX_HTML = resolve(REPO_ROOT, "public/index.html");
const APP_JS = resolve(REPO_ROOT, "public/app.js");

function extractInventory(src) {
  const re = /(?:const|let|var)\s+FONT_INVENTORY\s*=\s*\{/;
  const m = src.match(re);
  if (!m) throw new Error("FONT_INVENTORY not found");
  const openIdx = m.index + m[0].length - 1;
  let depth = 0;
  for (let i = openIdx; i < src.length; i++) {
    const c = src[i];
    if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) {
        const objSrc = src.slice(openIdx, i + 1);
        const fn = new Function("return (" + objSrc + ");");
        return fn();
      }
    }
  }
  throw new Error("Unbalanced braces for FONT_INVENTORY");
}

function familiesFromCss(css) {
  const families = new Set();
  for (const m of css.matchAll(/@font-face\s*\{[^}]*font-family:\s*'([^']+)'/g)) {
    families.add(m[1]);
  }
  return [...families];
}

function pickerFamilyNames(appSrc) {
  // Extract the COMFORT_FONTS picker allowlist. It's an array of
  // `{ value: "<Family Name>", label: "<Family Name>" }` entries; the
  // exposed name is the `value` field.
  const m = appSrc.match(/var\s+COMFORT_FONTS\s*=\s*\[([\s\S]*?)\];/);
  if (!m) throw new Error("COMFORT_FONTS not found");
  return [...m[1].matchAll(/value:\s*"([^"]+)"/g)].map((mm) => mm[1]);
}

describe("font inventory cross-source invariants", () => {
  test("core/font-inventory.js exists and parses", () => {
    const inv = extractInventory(readFileSync(INVENTORY, "utf-8"));
    expect(Object.keys(inv).length).toBeGreaterThan(0);
  });

  test("core/font-loader.js imports from the inventory (no FONT_FILES duplication)", () => {
    const loaderSrc = readFileSync(FONT_LOADER, "utf-8");
    expect(/require\(['"]\.\/font-inventory['"]\)/.test(loaderSrc)).toBe(true);
    expect(/(?:const|let|var)\s+FONT_FILES\s*=/.test(loaderSrc)).toBe(false);
  });

  test("every entry in the inventory has a woff2 file that exists and is valid wOF2", () => {
    const inv = extractInventory(readFileSync(INVENTORY, "utf-8"));
    const missing = [];
    for (const [family, faces] of Object.entries(inv)) {
      for (const face of faces) {
        const path = resolve(FONT_DIR, face.file);
        if (!existsSync(path)) {
          missing.push(`${family} → ${face.file}`);
          continue;
        }
        const buf = readFileSync(path);
        const magic = buf.subarray(0, 4).toString("latin1");
        if (magic !== "wOF2") missing.push(`${family} → ${face.file} (bad magic)`);
      }
    }
    expect(missing).toEqual([]);
  });

  test("fonts.css, index.html, and picker allowlist all agree with the inventory", () => {
    const inv = extractInventory(readFileSync(INVENTORY, "utf-8"));
    const invFamilies = Object.keys(inv);

    // fonts.css must declare exactly the inventory's families (auto-generated)
    const css = readFileSync(FONTS_CSS, "utf-8");
    const cssFamilies = familiesFromCss(css);
    expect(cssFamilies.sort()).toEqual(invFamilies.sort());
    expect(css).toContain("Auto-generated by scripts/build-fonts-css.mjs");

    // index.html must link fonts.css and have zero inline @font-face blocks
    const html = readFileSync(INDEX_HTML, "utf-8");
    const inline = [...html.matchAll(/<style>([\s\S]*?)<\/style>/g)].flatMap((m) =>
      [...m[1].matchAll(/@font-face\s*\{[^}]*font-family:\s*'([^']+)'/g)].map((fm) => fm[1])
    );
    expect(inline).toEqual([]);
    const links = [...html.matchAll(/<link[^>]*href="([^"]*fonts\.css[^"]*)"/g)].map((m) => m[1]);
    expect(links.length).toBeGreaterThan(0);
    expect(links[0]).toContain("fonts.css");

    // Picker allowlist (COMFORT_FONTS) must be a subset of the inventory
    const appSrc = readFileSync(APP_JS, "utf-8");
    const pickerNames = pickerFamilyNames(appSrc);
    const missing = pickerNames.filter((n) => !(n in inv));
    expect(missing).toEqual([]);
  });
});
