/**
 * Regression test: every font in the canonical inventory must have a
 * corresponding woff2 file on disk, the file must start with the wOF2
 * magic, and the auto-generated public/fonts.css must declare it.
 *
 * The single source of truth is core/font-inventory.js. Both
 * core/font-loader.js (server-side render, embeds as data URI) and
 * scripts/build-fonts-css.mjs (browser-side CSS, links woff2 files)
 * consume from there. This test pins down the invariants so the
 * picker, preview, and rendered output can't drift out of sync.
 */

import { describe, test, expect } from "bun:test";
import { readFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "..");
const INVENTORY = resolve(REPO_ROOT, "core/font-inventory.js");
const FONT_DIR = resolve(REPO_ROOT, "public/fonts");
const FONTS_CSS = resolve(REPO_ROOT, "public/fonts.css");
const FONT_LOADER = resolve(REPO_ROOT, "core/font-loader.js");
const INDEX_HTML = resolve(REPO_ROOT, "public/index.html");
const DOC_CSS = resolve(REPO_ROOT, "core/document-css.js");

function extractInventory(src) {
  // Pull out the FONT_INVENTORY = { ... }; object literal from the
  // inventory source. Single top-level block — eval safely in an
  // isolated function scope.
  const re = /(?:const|let|var)\s+FONT_INVENTORY\s*=\s*\{/;
  const m = src.match(re);
  if (!m) throw new Error("FONT_INVENTORY not found");
  const openIdx = m.index + m[0].length - 1;
  let depth = 0;
  for (let i = openIdx; i < src.length; i++) {
    const c = src[i];
    if (c === "{") depth++;
    else if (c === "}") {
      depth--;
      if (depth === 0) {
        const objSrc = src.slice(openIdx, i + 1);
        const fn = new Function("return (" + objSrc + ");");
        return fn();
      }
    }
  }
  throw new Error("Unbalanced braces for FONT_INVENTORY");
}

function extractFontLoaderInventory(src) {
  // font-loader.js re-exports FONT_INVENTORY. We can either read the
  // require()'d module via Bun, or re-parse the source. Parsing the
  // source is cheaper and isolates the test from runtime resolution.
  // We just check that it imports the inventory and uses it.
  const usesImport = /require\(['"]\.\/font-inventory['"]\)/.test(src);
  const hasOwnInventory = /(?:const|let|var)\s+FONT_FILES\s*=/.test(src);
  return { usesImport, hasOwnInventory };
}

function familiesFromCss(css) {
  const families = new Set();
  for (const m of css.matchAll(/@font-face\s*\{[^}]*font-family:\s*'([^']+)'/g)) {
    families.add(m[1]);
  }
  return [...families];
}

function familiesFromHtml(html) {
  // Look for a <link rel="stylesheet" href="fonts.css"> and any
  // inline @font-face blocks. Inline blocks are now expected to be empty.
  const inline = [];
  for (const m of html.matchAll(/<style>([\s\S]*?)<\/style>/g)) {
    for (const fm of m[1].matchAll(/@font-face\s*\{[^}]*font-family:\s*'([^']+)'/g)) {
      inline.push(fm[1]);
    }
  }
  const links = [...html.matchAll(/<link[^>]*href="([^"]*fonts\.css[^"]*)"/g)].map((m) => m[1]);
  return { inline, links };
}

describe("font inventory cross-source invariants", () => {
  test("core/font-inventory.js exists and parses", () => {
    const inv = extractInventory(readFileSync(INVENTORY, "utf-8"));
    expect(Object.keys(inv).length).toBeGreaterThan(0);
  });

  test("core/font-loader.js imports from the inventory (no FONT_FILES duplication)", () => {
    const loaderSrc = readFileSync(FONT_LOADER, "utf-8");
    const { usesImport, hasOwnInventory } = extractFontLoaderInventory(loaderSrc);
    expect(usesImport).toBe(true);
    expect(hasOwnInventory).toBe(false);
  });

  test("every entry in the inventory has a woff2 file that exists and is valid wOF2", () => {
    const inv = extractInventory(readFileSync(INVENTORY, "utf-8"));
    const missing = [];
    for (const [family, faces] of Object.entries(inv)) {
      for (const face of faces) {
        const path = resolve(FONT_DIR, face.file);
        if (!existsSync(path)) {
          missing.push(`${family} → ${face.file}`);
          continue;
        }
        const buf = readFileSync(path);
        const magic = buf.subarray(0, 4).toString("latin1");
        if (magic !== "wOF2") missing.push(`${family} → ${face.file} (bad magic)`);
      }
    }
    expect(missing).toEqual([]);
  });

  test("public/fonts.css declares exactly the inventory's families (auto-generated)", () => {
    const inv = extractInventory(readFileSync(INVENTORY, "utf-8"));
    const css = readFileSync(FONTS_CSS, "utf-8");
    const cssFamilies = familiesFromCss(css);
    const invFamilies = Object.keys(inv);
    expect(cssFamilies.sort()).toEqual(invFamilies.sort());
    // Header marker so humans know this file is generated, not hand-edited.
    expect(css).toContain("Auto-generated by scripts/build-fonts-css.mjs");
  });

  test("public/index.html links fonts.css and has zero inline @font-face blocks", () => {
    const html = readFileSync(INDEX_HTML, "utf-8");
    const { inline, links } = familiesFromHtml(html);
    expect(inline).toEqual([]);
    expect(links.length).toBeGreaterThan(0);
    expect(links[0]).toContain("fonts.css");
  });

  test("picker allowlist (COMFORT_FONTS) matches the inventory", () => {
    const docSrc = readFileSync(DOC_CSS, "utf-8");
    const m = docSrc.match(/const\s+COMFORT_FONTS\s*=\s*\{([^}]+)\}/);
    expect(m).not.toBeNull();
    const block = m[1];
    const pickerNames = [...block.matchAll(/^\s*([A-Za-z][A-Za-z0-9 ']+?)\s*:\s*true/gm)].map(
      (mm) => mm[1],
    );
    const inv = extractInventory(readFileSync(INVENTORY, "utf-8"));
    const missing = pickerNames.filter((n) => !(n in inv));
    expect(missing).toEqual([]);
  });
});