"""
flatwrite_extract.converter — AnyDoc / pdf-inspector / RapidOCR-backed extraction.

Converts in-memory document bytes to GitHub-Flavored Markdown using
`firecrawl-anydoc` (a Rust library with Python bindings). PDFs are routed
through the standalone `pdf-inspector` package because anydoc 0.1.6 bundles
an older pdf-inspector revision; the standalone Python package is newer and
produces better Markdown for many real-world PDFs. Images are converted via
`rapidocr-onnxruntime` (local, CPU-only OCR — no network call, no LLM).

The conversion runs locally: no network call, no LLM, no disk write.

Audio files are not converted; the caller should detect them and let
`rules.apply_rules()` emit a metadata-only stub.
"""
from __future__ import annotations

import anydoc


def convert_bytes(content: bytes, source_name: str, *, file_type: str) -> str:
    """Convert in-memory document bytes to markdown text.

    `source_name` must carry an extension so AnyDoc can pick the right
    parser (legacy .doc, .ppt, .xls and container variants like .docm,
    .xlsm, .ppsx all map to the canonical docx/pptx/xlsx formats
    automatically).

    `file_type` is the internal token from `validators.infer_type`.
    Audio types return an empty string because no transcription is
    available and the metadata stub is generated by `rules`. Images are
    converted via local OCR; if OCR finds no text, `rules` emits the
    metadata stub.

    Raises:
        ValueError: when `content` is empty.
        anydoc.UnsupportedError: when the format is not supported.
        anydoc.ConvertError: on corrupted, encrypted, or malformed files.
        RuntimeError: if conversion returns null/empty for a non-image/audio file.
    """
    if not content:
        raise ValueError("convert_bytes: content is empty")

    if file_type == "audio":
        # Metadata-only for audio; rules.py emits the stub.
        return ""

    if file_type == "image":
        return _convert_image(content)

    if file_type == "pdf":
        return _convert_pdf(content)

    fmt = anydoc.format_from_path(source_name)
    if fmt is None:
        raise anydoc.UnsupportedError(f"AnyDoc cannot determine a format for {source_name!r}")

    return anydoc.to_markdown_bytes(content, fmt)


def _convert_pdf(content: bytes) -> str:
    """Convert PDF bytes to Markdown using the latest pdf-inspector.

    anydoc 0.1.6 statically depends on pdf-inspector 0.1.7. The standalone
    `pdf-inspector` PyPI package is 0.2.6 and includes layout and table
    improvements. If it fails or is not installed, fall back to anydoc's
    built-in PDF conversion so the service still returns something useful.
    """
    try:
        import pdf_inspector

        result = pdf_inspector.process_pdf_bytes(content)
    except Exception:  # noqa: BLE001
        # pdf-inspector may be missing or fail on an unusual PDF; fall back
        # to anydoc's bundled (older) PDF pipeline rather than failing.
        fmt = anydoc.format_from_bytes(content)
        if fmt is None:
            fmt = "pdf"
        return anydoc.to_markdown_bytes(content, fmt)

    if result.markdown is not None and result.markdown.strip():
        return result.markdown

    # pdf-inspector can return None for image-only/scanned pages. Fall back
    # to anydoc to get whatever text it can before giving up.
    fmt = anydoc.format_from_bytes(content)
    if fmt is None:
        fmt = "pdf"
    return anydoc.to_markdown_bytes(content, fmt)


def _convert_image(content: bytes) -> str:
    """Convert image bytes to Markdown using local OCR (RapidOCR).

    RapidOCR is a CPU-only ONNX OCR engine (PaddleOCR models). No network
    call, no LLM, no GPU. Returns structured markdown with headings, bullet
    points, and paragraphs inferred from text position and font size.

    Returns empty string if no text is detected (e.g. a photograph with no
    text content). The caller's rule (`rules.image_metadata`) checks for
    empty output and emits the metadata stub in that case.
    """
    try:
        from .ocr import image_to_markdown

        return image_to_markdown(content)
    except Exception:  # noqa: BLE001
        # RapidOCR may be missing or fail on an unusual image. Return empty
        # so rules.py emits the metadata stub rather than crashing the API.
        return ""
