"""
flatwrite_extract.converter — AnyDoc-backed file extraction.

Converts in-memory document bytes to GitHub-Flavored Markdown using
`firecrawl-anydoc` (a Rust library with Python bindings). The conversion
runs locally: no network call, no LLM, no disk write.

Image and audio files are not converted; the caller should detect them
and let `rules.apply_rules()` emit a metadata-only stub. That keeps the
converter a single-responsibility document-to-markdown function.
"""
from __future__ import annotations

import anydoc


def convert_bytes(content: bytes, source_name: str, *, file_type: str) -> str:
    """Convert in-memory document bytes to markdown text.

    `source_name` must carry an extension so AnyDoc can pick the right
    parser (legacy .doc, .ppt, .xls and container variants like .docm,
    .xlsm, .ppsx all map to the canonical docx/pptx/xlsx formats
    automatically).

    `file_type` is the internal token from `validators.infer_type`.
    Image/audio types return an empty string because AnyDoc does not
    support them and the metadata stub is generated by `rules`.

    Raises:
        ValueError: when `content` is empty.
        anydoc.UnsupportedError: when AnyDoc does not recognize the format.
        anydoc.ConvertError: on corrupted, encrypted, or malformed files.
        RuntimeError: if AnyDoc returns a null/empty format for a non-image/audio file.
    """
    if not content:
        raise ValueError("convert_bytes: content is empty")

    if file_type in ("image", "audio"):
        # Metadata-only for binary media; rules.py emits the stub.
        return ""

    fmt = anydoc.format_from_path(source_name)
    if fmt is None:
        raise anydoc.UnsupportedError(f"AnyDoc cannot determine a format for {source_name!r}")

    return anydoc.to_markdown_bytes(content, fmt)
